version: '3'

env:
  CONSOLE_ADDR: 192.168.0.161:5000 # can be overriden in .env
dotenv: [".env"]

tasks:
  upload-150:
    aliases: [u5]
    desc: Upload build to console via FTP
    cmds:
    - lftp $CONSOLE_ADDR < scripts/lftp-upload-v150.sh

  upload-160:
    aliases: [u6]
    desc: Upload build to console via FTP
    cmds:
    - lftp $CONSOLE_ADDR < scripts/lftp-upload-v160.sh

  download:
    desc: Download logs and data from console ( -- <ADDRESS>)
    cmds:
    # - rm -f target/megaton-panic.txt
    - mkdir -p target/crash_reports/dumps
    - lftp $CONSOLE_ADDR < scripts/lftp-download.sh



